// Mock LLM integration for generating typing practice text
export async function InvokeLLM({ prompt }) {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 2000));
  
  // Paragraphs with 1-4 sentences
  const topics = [
    "The market square was alive with the sound of buskers.",
    "We boarded a ferry to cross the bay. The wind was brisk, and the sea spray cooled our faces. Seagulls followed closely, hoping for scraps. On the other side, a small fishing village awaited.",
    "We lit a fire in the hearth and watched the flames dance.",
    "We set up a tent in the back garden for the children. They brought out pillows, blankets, and a torch. The sound of crickets filled the warm summer night. By morning, they were still fast asleep inside.",
    "The windmill turned slowly in the evening breeze.",
    "The smell of fresh paint filled the hallway.",
    "We explored a second-hand shop filled with treasures. I left with an old map framed under glass.",
    "Fresh bread from the bakery still felt warm in my hands.",
    "The scent of freshly baked scones drifted from the kitchen.",
    "A candle flickered gently on the table.",
    "The sound of church bells welcomed the new year.",
    "The sun set behind the hills, painting the sky orange and pink.",
    "The scent of fresh mint filled the herb garden.",
    "We took a bus to a nearby village known for its cheese. The shopkeeper offered us generous samples to try. I left with a wedge wrapped carefully in brown paper.",
    "The café served tea in delicate porcelain cups.",
    "We wandered through a meadow dotted with wildflowers.",
    "The narrow lane was lined with cherry trees in full bloom. Pink petals drifted gently to the ground.",
    "The fox darted across the quiet road.",
    "The scent of roasted coffee beans filled the shop.",
    "A kite danced high in the spring breeze.",
    "We toasted marshmallows over an open fire on a chilly winter evening. The smell filled the air with warmth. Our neighbours joined us, bringing laughter and songs.",
    "The allotment was full of ripe vegetables ready for harvest.",
    "The first snow of the year fell overnight.",
    "The brass band played in the park on Sunday.",
    "The book I'm currently reading is incredibly engaging and has completely captured my attention. The author has a unique writing style that makes even the most complex topics accessible and interesting to read. I find myself staying up late at night just to finish one more chapter before going to sleep.",
    "We explored a small art gallery tucked away in a quiet street.",
    "The swans glided gracefully across the lake.",
    "We watched a rainbow appear after the afternoon rain.",
    "The old stone bridge was covered in ivy.",
    "The kettle whistled loudly from the kitchen.",
    "We made a comprehensive shopping list before heading to the grocery store yesterday morning. The list included essential items like milk, bread, eggs, and fresh vegetables for the week's meals. I also picked up some ingredients for the new recipe I want to try this weekend. The store was surprisingly busy for a weekday morning, but we managed to find everything we needed.",
    "We decided to spend the afternoon at the local swimming pool. The water was cool and refreshing after the hot walk there. Afterwards, we sat on the grass eating ice lollies.",
    "I found a pressed flower inside an old book.",
    "The smell of rain on warm pavement drifted through the open window. People hurried along the street with umbrellas in hand. Somewhere nearby, a dog barked.",
    "We walked along the pier as the tide came in. The smell of salt and seaweed filled the air.",
    "We planted tulip bulbs in neat rows.",
    "The scent of cinnamon filled the kitchen.",
    "We visited a farm shop in the countryside. Jars of homemade jam lined the shelves beside baskets of fresh eggs. Outside, chickens pecked at the grass while children fed the goats. The air smelled faintly of hay and fresh bread.",
    "The café was busy, but the smell of freshly brewed coffee made the wait worthwhile. I found a seat by the window and watched the rain.",
    "An antique clock chimed softly in the hallway.",
    "We took shelter under an old oak tree during the rain.",
    "The sound of a train echoed across the valley.",
    "The smell of waves against the harbour wall was calming.",
    "A robin perched on the garden fence, singing cheerfully.",
    "Icicles hung from the edge of the roof.",
    "I stopped at a small roadside stall for strawberries. They were still warm from the sun.",
    "We went for a night walk along the canal. Street lamps reflected in the still water. The sound of our footsteps echoed softly.",
    "The old railway station had been transformed into a bustling weekend market. Stalls were filled with fresh produce, handmade crafts, and the smell of hot pies baking. The sound of live music floated through the air as people wandered between the stands.",
    "The old cinema was showing a classic film for one night only. We queued outside with dozens of other fans. The smell of popcorn drifted through the doors. By the end, the audience applauded and cheered.",
    "A sudden gust scattered the papers across my desk.",
    "We played board games all evening with our family and had an absolute blast together. Everyone got really competitive during the strategy game, but we still managed to laugh and have fun throughout the night. The kids especially enjoyed the simpler games that we could all play together regardless of age.",
    "I found an old box of photographs in the attic. They showed scenes from summer holidays long past. Looking through them felt like stepping into another time.",
    "The path through the woods was carpeted with bluebells.",
    "The scent of lavender drifted from the fields nearby.",
    "We picked apples from the orchard.",
    "We watched fireworks light up the night sky.",
    "The postman whistled as he walked down the lane.",
    "The hills in the distance were dusted with snow.",
    "An old typewriter sat on the desk, its keys worn smooth.",
    "The cat curled up in the patch of sunlight.",
    "The sound of crackling logs filled the cosy cabin.",
    "We rode horses along the beach at low tide.",
    "We spotted a deer at the edge of the clearing.",
    "The old lighthouse stood tall against the grey sky. Waves crashed at its base with a steady rhythm.",
    "The coastal path wound along steep cliffs, offering stunning views of the waves below. Seagulls cried overhead as fishing boats bobbed in the distance. We stopped at a bench to enjoy the salty air and watch the horizon.",
    "We shared fish and chips by the seaside.",
    "A sudden shower sent everyone rushing under shop awnings.",
    "The garden gate creaked as it swung open.",
    "A small bakery had just opened at the end of our street. The owner greeted everyone with a smile and offered samples of freshly baked bread. It felt like a place that would quickly become part of the community.",
    "We visited a lighthouse and climbed to the very top.",
    "A hot air balloon drifted slowly over the fields.",
    "We wandered through the old castle ruins. The stone walls were covered in moss.",
    "My sister helped me with my maths homework for over two hours yesterday evening. She's really good at explaining complex concepts in a way that makes them easy to understand. We worked through several difficult problems together, and she showed me different methods to solve each one.",
    "The movie we watched last night was absolutely incredible and exceeded all our expectations. The plot was engaging from start to finish with unexpected twists that kept us guessing throughout the entire film. The acting was superb, especially the lead actress who delivered a powerful performance in the emotional scenes.",
    "We built a sandcastle and decorated it with shells.",
    "The morning air was crisp and smelled faintly of pine.",
    "The air was filled with the sound of church bells. It made the whole village feel timeless.",
    "My best friend called me yesterday evening to catch up on everything that's been happening in our lives. We talked for over an hour about our weekend plans and the new restaurant that just opened downtown. She mentioned wanting to try their famous pasta dishes and suggested we make a reservation for next Friday.",
    "We went cycling along the riverbank. Ducks paddled in the water while families picnicked on the grass. The sound of the bicycle wheels on the gravel path was relaxing.",
    "The library was warm and quiet, the perfect place to read.",
    "We wandered through a meadow dotted with wildflowers.",
    "The small rowboat drifted lazily along the river as the sun rose. Birds called to one another from the reeds. The water reflected the pink and orange sky like a mirror.",
    "We watched swallows swoop over the lake, diving for insects in the golden light. Their wings shimmered in the sun. I felt completely at peace as we sat by the shore.",
    "The bakery smelled of warm bread and sweet pastries. I chose a croissant and a tart. Outside, the street was bustling with morning shoppers.",
    "Autumn leaves crunched under our feet as we walked through the park. The air smelled of damp earth. Children laughed as they kicked the leaves up into the air.",
    "The garden was bursting with colour, from tulips to marigolds and roses. Bees buzzed busily between the flowers. We spent hours simply wandering and admiring the blooms.",
    "A distant train whistle echoed through the valley in the quiet evening. Smoke rose faintly from the engine. The sound reminded me of childhood journeys.",
    "We found a quiet bench under an old oak and read in the dappled sunlight. The shadows of the leaves danced across the pages. Time seemed to slow as we lost ourselves in the stories.",
    "A small hedgehog scurried across the lawn and disappeared into the bushes. The garden remained quiet after it went.",
    "The lighthouse beam swept across the waves, warning ships of the rocks below. Waves crashed against the cliff with a steady rhythm.",
    "The old bookshop had dusty shelves and a faint smell of parchment. I spent ages browsing the forgotten tomes.",
    "A soft breeze carried the scent of freshly cut grass through the meadow. Flowers swayed gently in the wind.",
    "We picked wildflowers along the lane and made a small bouquet for the table. Their colours brightened up the kitchen instantly.",
    "The ferry rocked gently as we sailed across the harbour at sunset.",
    "The churchyard was quiet, with gravestones leaning under centuries of ivy.",
    "The sun dipped below the hills, casting long shadows across the fields. We walked along the old lane, crunching the dried leaves beneath our feet. A cold breeze rustled the branches above, and the distant sound of a dog barking echoed across the valley. It felt as if the whole world had slowed for just a moment."
];

  
  // Return a random topic for now
  return topics[Math.floor(Math.random() * topics.length)];
} 